#ifndef MLEKM_CONSTANS_H
#define MLEKM_CONSTANS_H

#define MLEKM_EC_ADDR 0x00
#define MLEKM_EC_LEN 256

#define MLEKM_EC_VERSION_ADDR 0xA0
#define MLEKM_EC_VERSION_LEN 12

#define MLEKM_FAN_RPM_DIVIDEND 478000

// CPU
#define MLEKM_CPU_REALTIME_TEMP_LEN 1
#define MLEKM_CPU_REALTIME_FAN_SPEED_LEN 1
#define MLEKM_CPU_REALTIME_FAN_RPM_LEN 2
#define MLEKM_CPU_TEMPS_LEN 6
#define MLEKM_CPU_FAN_SPEEDS_LEN 7

// GPU
#define MLEKM_GPU_REALTIME_TEMP_LEN 1
#define MLEKM_GPU_REALTIME_FAN_SPEED_LEN 1
#define MLEKM_GPU_REALTIME_FAN_RPM_LEN 2
#define MLEKM_GPU_TEMPS_LEN 6
#define MLEKM_GPU_FAN_SPEEDS_LEN 7

#define MLEKM_FAN_MODE_LEN 1
#define MLEKM_COOLER_BOOST_STATUS_LEN 1

enum MLEKM_FAN_MODE {
    MLEKM_FAN_MODE_UNKNOWN = 0,
    MLEKM_FAN_MODE_AUTO,
    MLEKM_FAN_MODE_BASIC,
    MLEKM_FAN_MODE_ADVANCED
};

enum MLEKM_COOLER_BOOST_STATUS {
    MLEKM_COOLER_BOOST_STATUS_UNKNOWN = 0,
    MLEKM_COOLER_BOOST_STATUS_ONN,
    MLEKM_COOLER_BOOST_STATUS_OFF,
};

#endif // MLEKM_CONSTANS_H